# DAY 4 - NumPy: Foundation of Data Science

**NumPy** = Numerical Python

Why NumPy?
- Faster than Python lists (uses C internally)
- Supports multi-dimensional arrays
- 400+ built-in math functions
- Foundation of Pandas, Matplotlib, Scikit-learn

---

## Topics Covered
1. Array Creation
2. Array Properties
3. Indexing and Slicing
4. Array Operations
5. Reshaping
6. Statistical Functions
7. Math Functions
8. Random Module
9. Broadcasting
10. Linear Algebra
11. Real-world Practice Problems

In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.3.5


**Explanation:** `import numpy as np` loads the NumPy library under the short alias `np` (the standard convention). `np.__version__` tells us which version is installed, which is useful for checking compatibility.

---
## 1. Array Creation

Different ways to create NumPy arrays.

In [2]:
# From Python list
a1 = np.array([10, '20', 30, 40, 50])
print('1D Array:', a1)
print('Type:', type(a1))
print('dtype:', a1.dtype)

1D Array: ['10' '20' '30' '40' '50']
Type: <class 'numpy.ndarray'>
dtype: <U21


**Explanation:** `np.array()` converts a Python list into a NumPy array. Here the list mixes numbers and a string (`'20'`), so NumPy **upcasts everything to a single dtype** — in this case a Unicode string (`<U21`). This shows that all elements of a NumPy array must share the same dtype, unlike a Python list.

In [3]:
# 2D Array (Matrix)
a2 = np.array([
  [12,23],
  [34,45],
  [56,67]
])
print('2D Array (Matrix):')
print(a2)

2D Array (Matrix):
[[12 23]
 [34 45]
 [56 67]]


**Explanation:** Passing a list of lists creates a **2D array** (matrix) — each inner list becomes a row. This array has shape `(3, 2)`: 3 rows and 2 columns.

In [4]:
# 3D Array
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print('3D Array:')
print(a3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Explanation:** Nesting lists one level deeper creates a **3D array**, shape `(2, 2, 2)` — think of it as 2 "layers", each containing a 2x2 matrix. 3D+ arrays are common for things like image data (height, width, color channels) or batches of matrices.

In [5]:
# Special arrays
print('Zeros (3x4):')
print(np.zeros((4, 5)))

print('\nOnes (2x3):')
print(np.ones((2, 3)))

print('\nIdentity Matrix (8x8):')
print(np.eye(4))

print('\nFull (fill with 7):')
print(np.full((4, 4), 7))

Zeros (3x4):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix (8x8):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Full (fill with 7):
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


**Explanation:** These are shortcut functions to create arrays without typing every value:
- `np.zeros((4, 5))` — array of all 0s with shape (4, 5)
- `np.ones((2, 3))` — array of all 1s with shape (2, 3)
- `np.eye(4)` — a 4x4 **identity matrix** (1s on the diagonal, 0s elsewhere)
- `np.full((4, 4), 7)` — array filled entirely with the value 7

These are handy for initializing arrays before filling them with real data.

In [6]:
# arange - like Python range()
print('arange(10):', np.arange(20))

print('arange(1, 20, 2):', np.arange(2,40,5))

# linspace - evenly spaced values
print('\nlinspace(0, 1, 5):', np.linspace(0, 1, 5))

print('linspace(0, 100, 6):', np.linspace(0, 100, 6))

arange(10): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arange(1, 20, 2): [ 2  7 12 17 22 27 32 37]

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(0, 100, 6): [  0.  20.  40.  60.  80. 100.]


**Explanation:**
- `np.arange(start, stop, step)` — like Python's `range()`, but returns a NumPy array. `stop` is excluded.
- `np.linspace(start, stop, num)` — generates `num` evenly spaced values between `start` and `stop` (inclusive on both ends). Useful when you know how many points you want, rather than the step size.

---
## 2. Array Properties

Key attributes every data scientist should know.

In [7]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12]
])

print('Array:')
print(arr)
print()
print('ndim  (dimensions):', arr.ndim)
print('shape (rows, cols):', arr.shape)
print('size  (total elements):', arr.size)
print('dtype (data type):', arr.dtype)
print('itemsize (bytes per element):', arr.itemsize)
print('nbytes (total memory):', arr.nbytes, 'bytes')

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

ndim  (dimensions): 2
shape (rows, cols): (3, 4)
size  (total elements): 12
dtype (data type): int64
itemsize (bytes per element): 8
nbytes (total memory): 96 bytes


**Explanation:** These attributes describe an array's structure (no parentheses — they're properties, not functions):
- `.ndim` — number of dimensions (axes)
- `.shape` — a tuple of (rows, columns, ...) sizes
- `.size` — total number of elements (rows × columns)
- `.dtype` — the data type of the elements (e.g., `int64`, `float64`)
- `.itemsize` — bytes used by **one** element
- `.nbytes` — total memory used by the whole array (`size × itemsize`)

---
## 3. Indexing and Slicing

Accessing elements in arrays.

In [8]:
# 1D Indexing
marks = np.array([85, 92, 78, 95, 88, 70, 65])
print('All marks:', marks)
print('First mark:', marks[0])
print('Last mark:', marks[-1])
print('Marks 2 to 5:', marks[1:5])
print('Every 2nd mark:', marks[::2])
print('Reversed:', marks[::-1])

All marks: [85 92 78 95 88 70 65]
First mark: 85
Last mark: 65
Marks 2 to 5: [92 78 95 88]
Every 2nd mark: [85 78 88 65]
Reversed: [65 70 88 95 78 92 85]


**Explanation:** 1D array indexing works like Python lists:
- `marks[0]` — first element, `marks[-1]` — last element
- `marks[1:5]` — slice from index 1 up to (not including) index 5
- `marks[::2]` — every 2nd element (step = 2)
- `marks[::-1]` — reverses the array (step = -1)

In [9]:
# 2D Indexing - [row, column]
grid = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print('Grid:')
print(grid)
print()
print('Row 0:', grid[0])
print('Element at row=1, col=2:', grid[1, 2])
print('Column 1:', grid[:, 1])
print('Sub-matrix (2x2):')
print(grid[0:2, 0:2])

Grid:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Row 0: [10 20 30]
Element at row=1, col=2: 60
Column 1: [20 50 80]
Sub-matrix (2x2):
[[10 20]
 [40 50]]


**Explanation:** For 2D arrays, indexing uses `grid[row, column]`:
- `grid[0]` — the entire first row
- `grid[1, 2]` — single element at row 1, column 2
- `grid[:, 1]` — `:` means "all rows", so this grabs the entire column at index 1
- `grid[0:2, 0:2]` — a sub-matrix: rows 0–1 and columns 0–1 (slicing both axes at once)

In [10]:
print('Row 0:', grid[0])
print(grid[2])


Row 0: [10 20 30]
[70 80 90]


In [11]:
print('Element at row=1, col=2:', grid[1, 2])

Element at row=1, col=2: 60


In [12]:
print('Column 1:', grid[:, 1])

Column 1: [20 50 80]


In [13]:
print('Sub-matrix (2x2):')
print(grid[0:2, 0:2])

Sub-matrix (2x2):
[[10 20]
 [40 50]]


In [14]:
print(grid[0:2, 0:2])

[[10 20]
 [40 50]]


In [15]:
# Boolean Indexing (Filtering)
scores = np.array([55, 72, 88, 44, 91, 63, 79])

print('All scores:', scores)


All scores: [55 72 88 44 91 63 79]


**Explanation: Boolean Indexing.** Writing a condition like `scores > 70` produces an array of `True`/`False` values (one per element). Using that boolean array inside `[]` filters the original array, keeping only elements where the condition is `True`. You can combine conditions with `&` (and) / `|` (or) — note the extra parentheses are required, e.g. `(scores >= 60) & (scores <= 80)`.

In [16]:
print('Scores > 70:', scores[scores > 70])

Scores > 70: [72 88 91 79]


In [17]:
print('Scores > 70:', scores[scores >= 63])

Scores > 70: [72 88 91 63 79]


In [18]:
print('Scores > 70:', scores[scores == 63])


Scores > 70: [63]


In [19]:
print('Scores > 70:', scores[scores < 70])

Scores > 70: [55 44 63]


In [20]:
print('Scores between 60-80:', scores[(scores >= 60) & (scores <= 80)])


Scores between 60-80: [72 63 79]


In [21]:
print('Pass (>=50):', scores[scores >= 50])

Pass (>=50): [55 72 88 91 63 79]


---
## 4. Array Operations

Element-wise operations (vectorized = very fast).

In [22]:
import numpy as np
a = np.array([10, 20, 30, 40,])
b = np.array([2, 4, 6, 8])
print('a :', a)

a : [10 20 30 40]


**Explanation: Vectorized Operations.** When you apply `+`, `-`, `*`, `/`, `**`, `%`, `//` between two arrays of the same shape, NumPy applies the operation **element-by-element** automatically — no loop needed. This is both more concise and much faster than looping in plain Python, because the operation runs in optimized C code under the hood.

In [23]:
print('b :', b)

b : [2 4 6 8]


In [24]:
print('a + b :', a + b)


a + b : [12 24 36 48]


In [25]:
print('a / b    :', a / b)


a / b    : [5. 5. 5. 5.]


In [26]:
print('a ** 2   :', a ** 2)


a ** 2   : [ 100  400  900 1600]


In [27]:
print('a % 3    :', a % 3)


a % 3    : [1 2 0 1]


In [28]:
print('a // 3   :', a // 3)

a // 3   : [ 3  6 10 13]


In [29]:
# Scalar operations
prices = np.array([100, 200, 150, 300, 250])

print('Original prices:', prices)

print('10% discount:', prices * 0.1)

print('10% discount:', prices * 0.9)

print('Add GST 18%:', prices * 1.18)

print('Price > 200:', prices > 200)

Original prices: [100 200 150 300 250]
10% discount: [10. 20. 15. 30. 25.]
10% discount: [ 90. 180. 135. 270. 225.]
Add GST 18%: [118. 236. 177. 354. 295.]
Price > 200: [False False False  True  True]


**Explanation: Scalar Operations.** A single number (scalar) is automatically applied to every element of the array — e.g. `prices * 0.9` reduces every price by 10%. Comparison operators (`>`, `<`, `==`) also work element-wise, returning a boolean array, e.g. `prices > 200`.

---
## 5. Reshaping Arrays

Changing the shape without changing data.

In [30]:
data = np.arange(1, 13)
print(data)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Explanation:** `np.arange(1, 13)` creates a 1D array with 12 elements (1 through 12). This will be reshaped below into different dimensions to show how the same data can be viewed in different shapes.

In [31]:
# Reshape to 3x4
m1 = data.reshape(3, 4)

print(m1)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Explanation:** `.reshape(3, 4)` rearranges the 12 elements into 3 rows × 4 columns. The total element count must stay the same (3 × 4 = 12) or NumPy raises an error.

In [32]:
# Reshape to 4x3
m2 = data.reshape(4, 3)
print('\nReshaped to 4x3:')
print(m2)




Reshaped to 4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Explanation:** Same 12 elements, reshaped to 4 rows × 3 columns instead. Reshaping doesn't copy or change the data — it just changes how it's organized/viewed.

In [33]:
# Reshape to 2x2x3 (3D)
m3 = data.reshape(2, 2, 3)
print('\nReshaped to 2x2x3 (3D):')
print(m3)


Reshaped to 2x2x3 (3D):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Explanation:** `.reshape(2, 2, 3)` turns the 12 elements into a 3D array: 2 blocks, each containing a 2×3 matrix. Again, 2×2×3 = 12, so the element count matches.

In [34]:
# Flatten (back to 1D)
print('Flattened:', m3.flatten())

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


**Explanation:** `.flatten()` collapses any multi-dimensional array back into a single 1D array, in row-major (left-to-right, top-to-bottom) order.

In [35]:
# Transpose (rows <-> columns)
print('\nOriginal:')
print(m1)
print('\nTransposed:')
print(m1.T)


Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Explanation:** `.T` (transpose) flips an array across its diagonal — rows become columns and columns become rows. A (3,4) shaped array becomes (4,3) after transposing.

---
## 6. Statistical Functions

Built-in stats — used in every data analysis.

In [36]:
student_marks = np.array([72, 85, 91, 64, 78, 88, 55, 93, 70, 82])
print('Marks:', student_marks)
print('Mean (Average)  :', np.mean(student_marks))
print('Median          :', np.median(student_marks))
print('Std Deviation   :', round(np.std(student_marks), 2))
print('Variance        :', round(np.var(student_marks), 2))
print('Min             :', np.min(student_marks))
print('Max             :', np.max(student_marks))
print('Sum             :', np.sum(student_marks))
print('25th Percentile :', np.percentile(student_marks, 25))
print('75th Percentile :', np.percentile(student_marks, 75))
print('Range           :', np.ptp(student_marks))

Marks: [72 85 91 64 78 88 55 93 70 82]
Mean (Average)  : 77.8
Median          : 80.0
Std Deviation   : 11.76
Variance        : 138.36
Min             : 55
Max             : 93
Sum             : 778
25th Percentile : 70.5
75th Percentile : 87.25
Range           : 38


**Explanation: Statistical Functions.**
- `np.mean` — average value
- `np.median` — middle value when sorted
- `np.std` — standard deviation (spread of data around the mean)
- `np.var` — variance (std squared)
- `np.min` / `np.max` — smallest/largest value
- `np.sum` — total of all elements
- `np.percentile(arr, p)` — value below which `p`% of the data falls
- `np.ptp` (peak-to-peak) — range = max − min

In [37]:
# Row-wise and column-wise stats
sales_matrix = np.array([
    [100, 200, 150],
    [130, 180, 160],
    [140, 220, 170],
])

print('Sales Matrix (rows=months, cols=products):')
print(sales_matrix)
print()
print('Total per product (column-wise sum):', np.sum(sales_matrix, axis=0))
print('Total per month (row-wise sum)     :', np.sum(sales_matrix, axis=1))
print('Average per product                :', np.mean(sales_matrix, axis=0))
print('Average per month                  :', np.mean(sales_matrix, axis=1))


Sales Matrix (rows=months, cols=products):
[[100 200 150]
 [130 180 160]
 [140 220 170]]

Total per product (column-wise sum): [370 600 480]
Total per month (row-wise sum)     : [450 470 530]
Average per product                : [123.33333333 200.         160.        ]
Average per month                  : [150.         156.66666667 176.66666667]


**Explanation: The `axis` parameter.** For 2D arrays, stats functions can be applied along a specific direction instead of over the whole array:
- `axis=0` — operate **down each column** (collapses rows), giving one result per column
- `axis=1` — operate **across each row** (collapses columns), giving one result per row

This is one of the most important concepts in NumPy/Pandas for summarizing tabular data.

---
## 7. Math Functions

In [38]:
x = np.array([144, 4, 9, 16, 25])
print('x', x)


x [144   4   9  16  25]


In [39]:
print('sqrt(x)   :', np.sqrt(x))


sqrt(x)   : [12.  2.  3.  4.  5.]


In [40]:
print('log(x)    :', np.log(x).round(2))


log(x)    : [4.97 1.39 2.2  2.77 3.22]


In [41]:
print('log2(x)   :', np.log2(x).round(2))


log2(x)   : [7.17 2.   3.17 4.   4.64]


In [42]:
print('log10(x)  :', np.log10(x).round(2))


log10(x)  : [2.16 0.6  0.95 1.2  1.4 ]


In [43]:
print('exp(x)    :', np.exp([1, 2, 3]).round(2))


exp(x)    : [ 2.72  7.39 20.09]


In [44]:
print('abs(x)    :', np.abs([-3, -1, 2, -5]))

abs(x)    : [3 1 2 5]


In [45]:
print('round     :', np.round([3.14159, 2.71828], 3))

round     : [3.142 2.718]


In [46]:
print('floor     :', np.floor([6.9, 2.5, 3.1]))

floor     : [6. 2. 3.]


**Explanation: Math Functions.**
- `np.sqrt(x)` — square root of each element
- `np.log(x)` — natural log (base *e*)
- `np.log2(x)` / `np.log10(x)` — log base 2 / base 10
- `np.exp(x)` — *e* raised to the power of each element (inverse of `np.log`)
- `np.abs(x)` — absolute value (drops the sign)
- `np.round(x, n)` — round to `n` decimal places
- `np.ceil(x)` — round **up** to the nearest whole number
- `np.floor(x)` — round **down** to the nearest whole number

All of these are vectorized: they apply to every element at once, no loop required.

---
## 8. Random Module

Used in data science for simulations, sampling, testing.

In [47]:
np.random.seed(42)  # Fix the random seed so results are the same every time we run this cell

print('Random integers (1-100, size=5):')
print(np.random.randint(1, 100, size=5))  # 5 random whole numbers between 1 (inclusive) and 100 (exclusive)


Random integers (1-100, size=5):
[52 93 15 72 61]


In [48]:

print('\nRandom floats (0-1, size=5):')
print(np.random.random(5).round(4))  # 5 random decimals between 0 and 1, rounded to 4 places



Random floats (0-1, size=5):
[0.5969 0.4458 0.1    0.4592 0.3337]


In [49]:

print('\nNormal distribution (mean=0, std=1, size=5):')
print(np.random.normal(0, 1, 4).round(4))  # 5 values from a normal (bell curve) distribution, mean=0, std=1



Normal distribution (mean=0, std=1, size=5):
[ 0.3926 -0.9292  0.0798 -0.1595]


In [50]:

print('\nNormal (mean=50000, std=10000, 5 salaries):')
salaries = np.random.normal(50000, 10000, 5).astype(int)  # 5 simulated salaries around 50000, std dev 10000, converted to int
print(salaries)



Normal (mean=50000, std=10000, 5 salaries):
[50222 45722 44681 48825 52220]


In [51]:

print('\nRandom choice from array:')
names = ['Alice', 'Bob', 'Charlie', 'Diana']
print(np.random.choice(names, size=3))  # randomly pick 3 names from the list (with replacement by default)


Random choice from array:
['Diana' 'Charlie' 'Diana']


**Explanation: Random Module.**
- `np.random.seed(42)` fixes the random number generator so results are reproducible every run.
- `np.random.randint(low, high, size)` — random integers in `[low, high)`
- `np.random.random(size)` — random floats in `[0, 1)`
- `np.random.normal(mean, std, size)` — samples from a normal (bell curve) distribution
- `np.random.choice(array, size)` — randomly picks elements from a given array (with replacement by default)

---
## 9. Broadcasting

NumPy can do operations on arrays of different shapes automatically.

In [52]:
# Scalar + Array
arr = np.array([10000, 200000, 30000, 40000, 50000])
print('Array + 10:', arr + 1000)
# 2D + 1D broadcasting
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
bonuses = np.array([100, 200, 300])
print('\nMatrix:')
print(matrix)
print('\nBonuses (added to each row):', bonuses)
print('\nMatrix + Bonuses:')

print(matrix + bonuses)

Array + 10: [ 11000 201000  31000  41000  51000]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Bonuses (added to each row): [100 200 300]

Matrix + Bonuses:
[[101 202 303]
 [104 205 306]
 [107 208 309]]


**Explanation: Broadcasting.** NumPy lets you combine arrays of different shapes without manually duplicating data, as long as their shapes are "compatible." Here, the 1D `bonuses` array (shape `(3,)`) is automatically "stretched" to match each row of the 2D `matrix` (shape `(3,3)`), so it gets added to every row. This avoids writing explicit loops.

In [53]:
# Real-world: Normalize data (0 to 1 scaling)
raw_data = np.array([200, 500, 300, 800, 100, 600])

min=raw_data.min()

normalized = (raw_data - raw_data.min()) / (raw_data.max() - raw_data.min())

print('Raw data  :', raw_data)
print('Normalized:', normalized.round(3))

Raw data  : [200 500 300 800 100 600]
Normalized: [0.143 0.571 0.286 1.    0.    0.714]


**Explanation: Min-Max Normalization.** `(x - min) / (max - min)` rescales any dataset so every value falls between 0 and 1, while preserving relative order/spacing. This is a common preprocessing step before feeding data into machine learning models.

---
## 10. Linear Algebra

Used in Machine Learning algorithms.

In [54]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('Matrix A:')
print(A)
print('\nMatrix B:')
print(B)

print('\nMatrix Multiplication (A @ B):')
print(A @ B)

print('\nDot Product:')

print(np.dot(A, B))

print('\nDeterminant of A:', np.linalg.det(A))

print('\nInverse of A:')
print(np.linalg.inv(A).round(2))

print('\nEigenvalues of A:')
eigenvalues, eigenvectors = np.linalg.eig(A)
print('Values:', eigenvalues.round(2))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Dot Product:
[[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues of A:
Values: [-0.37  5.37]


**Explanation: Linear Algebra.**
- `A @ B` or `np.dot(A, B)` — matrix multiplication (not element-wise!)
- `np.linalg.det(A)` — determinant, a single number summarizing certain properties of the matrix (e.g., 0 means the matrix isn't invertible)
- `np.linalg.inv(A)` — the inverse matrix, such that `A @ inv(A)` ≈ identity matrix
- `np.linalg.eig(A)` — eigenvalues and eigenvectors, fundamental to PCA and many ML algorithms

These operations are the backbone of how machine learning models work under the hood (e.g., linear regression, PCA, neural networks).

---
## 11. Useful Utility Functions

In [55]:
# Sort
arr = np.array([42, 7, 19, 55, 3, 28])
print('Original:', arr)
print('Sorted  :', np.sort(arr))


print('Argsort (indices):', np.argsort(arr))

# Where (conditional)
marks = np.array([72, 45, 88, 38, 91, 55])
result = np.where(marks >= 50, 'Pass', 'Fail')
print('\nMarks  :', marks)
print('Result :', result)

# Unique
cities = np.array(['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai'])
print('\nAll cities:', cities)
print('Unique cities:', np.unique(cities))

Original: [42  7 19 55  3 28]
Sorted  : [ 3  7 19 28 42 55]
Argsort (indices): [4 1 2 5 0 3]

Marks  : [72 45 88 38 91 55]
Result : ['Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass']

All cities: ['Delhi' 'Mumbai' 'Delhi' 'Chennai' 'Mumbai']
Unique cities: ['Chennai' 'Delhi' 'Mumbai']


**Explanation: Utility Functions.**
- `np.sort(arr)` — returns a sorted copy of the array
- `np.argsort(arr)` — returns the **indices** that would sort the array (useful to sort one array based on another)
- `np.where(condition, value_if_true, value_if_false)` — element-wise if/else, returns a new array
- `np.unique(arr)` — returns sorted unique values, removing duplicates

In [56]:
# Stack and Concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('Horizontal stack:', np.hstack([a, b]))
print('Vertical stack:')
print(np.vstack([a, b]))

# Concatenate
print('Concatenate:', np.concatenate([a, b]))

Horizontal stack: [1 2 3 4 5 6]
Vertical stack:
[[1 2 3]
 [4 5 6]]
Concatenate: [1 2 3 4 5 6]


**Explanation: Combining Arrays.**
- `np.hstack([a, b])` — stacks arrays side by side (horizontally), extending the length
- `np.vstack([a, b])` — stacks arrays on top of each other (vertically), creating new rows
- `np.concatenate([a, b])` — joins arrays along a given axis (default axis 0); `hstack`/`vstack` are convenience wrappers around this

---
## 12. Real-World Practice Problems

In [57]:
# Problem 1: Student Grade Analysis
np.random.seed(10)
student_scores = np.random.randint(40, 100, size=(5, 4))
subjects = ['Math', 'Science', 'English', 'History']
students = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve']

print('Score Sheet:')
print('Subjects:', subjects)
for i, student in enumerate(students):
    print(f'{student}: {student_scores[i]}')

print('\nClass Average per Subject:', np.mean(student_scores, axis=0).round(1))
print('Average per Student:', np.mean(student_scores, axis=1).round(1))
print('Highest scorer:', students[np.argmax(np.mean(student_scores, axis=1))])
print('Topper subject:', subjects[np.argmax(np.mean(student_scores, axis=0))])

Score Sheet:
Subjects: ['Math', 'Science', 'English', 'History']
Alice: [49 76 55 40]
Bob: [89 99 68 65]
Charlie: [69 88 69 89]
Diana: [98 48 49 40]
Eve: [82 80 94 76]

Class Average per Subject: [77.4 78.2 67.  62. ]
Average per Student: [55.  80.2 78.8 58.8 83. ]
Highest scorer: Eve
Topper subject: Science


**Explanation:** This combines several concepts learned above: `np.random.randint` generates a 5×4 score matrix (5 students × 4 subjects), `axis=0`/`axis=1` means give per-subject and per-student averages, and `np.argmax` finds the **index** of the highest value — used here to look up the corresponding student/subject name.

In [58]:
# Problem 2: Sales Analysis
np.random.seed(5)
monthly_sales = np.random.randint(50000, 200000, size=12)
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

print('Monthly Sales:')
for m, s in zip(months, monthly_sales):
    print(f'  {m}: Rs {s:,}')

print(f'\nTotal Annual Sales: Rs {monthly_sales.sum():,}')
print(f'Average Monthly Sales: Rs {monthly_sales.mean():,.0f}')
print(f'Best Month: {months[np.argmax(monthly_sales)]} - Rs {monthly_sales.max():,}')
print(f'Worst Month: {months[np.argmin(monthly_sales)]} - Rs {monthly_sales.min():,}')

# Growth rate
growth = np.diff(monthly_sales) / monthly_sales[:-1] * 100
print(f'\nAvg Month-on-Month Growth: {growth.mean():.2f}%')

Monthly Sales:
  Jan: Rs 85,683
  Feb: Rs 68,638
  Mar: Rs 70,463
  Apr: Rs 174,605
  May: Rs 171,974
  Jun: Rs 186,592
  Jul: Rs 109,465
  Aug: Rs 83,800
  Sep: Rs 84,750
  Oct: Rs 101,824
  Nov: Rs 70,176
  Dec: Rs 113,515

Total Annual Sales: Rs 1,321,485
Average Monthly Sales: Rs 110,124
Best Month: Jun - Rs 186,592
Worst Month: Feb - Rs 68,638

Avg Month-on-Month Growth: 11.34%


**Explanation:** `np.argmax`/`np.argmin` find the index of the best/worst month. `np.diff(arr)` computes the difference between consecutive elements (`arr[i+1] - arr[i]`), which combined with `monthly_sales[:-1]` (all but the last element) calculates the **month-on-month growth rate** as a percentage.

In [59]:
# Problem 3: Stock Price Simulation
np.random.seed(42)
days = 30
initial_price = 1000
daily_returns = np.random.normal(0.001, 0.02, days)  # 0.1% avg return, 2% std

stock_prices = initial_price * np.cumprod(1 + daily_returns)
stock_prices = np.round(stock_prices, 2)

print('Stock Price Analysis (30 days):')
print(f'Starting Price: Rs {initial_price}')
print(f'Final Price   : Rs {stock_prices[-1]}')
print(f'Max Price     : Rs {stock_prices.max()}')
print(f'Min Price     : Rs {stock_prices.min()}')
print(f'Avg Price     : Rs {stock_prices.mean():.2f}')
profit_loss = stock_prices[-1] - initial_price
print(f'Profit/Loss   : Rs {profit_loss:.2f} ({profit_loss/initial_price*100:.2f}%)')

Stock Price Analysis (30 days):
Starting Price: Rs 1000
Final Price   : Rs 916.02
Max Price     : Rs 1103.18
Min Price     : Rs 916.02
Avg Price     : Rs 1009.05
Profit/Loss   : Rs -83.98 (-8.40%)


**Explanation:** This simulates a stock price walk: `np.random.normal` generates 30 random daily returns, and `np.cumprod(1 + daily_returns)` computes the **cumulative product**, compounding each day's return on top of the previous days — this is how compound growth/decline is modeled.

---
## Summary - What You Learned

| Concept | Function |
|---------|----------|
| Create array | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()` |
| Properties | `.shape`, `.ndim`, `.size`, `.dtype` |
| Indexing | `arr[0]`, `arr[1:3]`, `arr[row, col]` |
| Boolean filter | `arr[arr > 5]` |
| Math | `np.sqrt()`, `np.log()`, `np.exp()` |
| Stats | `np.mean()`, `np.std()`, `np.percentile()` |
| Reshape | `.reshape()`, `.flatten()`, `.T` |
| Random | `np.random.randint()`, `np.random.normal()` |
| Linear Algebra | `np.dot()`, `np.linalg.inv()` |
| Utility | `np.sort()`, `np.where()`, `np.unique()` |

---
## Homework

1. Create a 5x5 matrix with random integers between 1-50
2. Find the sum of each row and each column
3. Normalize the matrix (values between 0 and 1)
4. Find all values greater than 25
5. Create an employee salary array and find how many earn above average